name: Build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_type:
          - "-O0 -ggdb3"
          - "-O2"
        compiler:
          - { CC: gcc, CXX: g++ }
          - { CC: clang, CXX: clang++ }

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build
      working-directory: ${{runner.workspace}}
      shell: bash
      env:
        CFLAGS: ${{ matrix.build_type }}
        CXXFLAGS: ${{ matrix.build_type }}
      run: make

    - name: Test
      working-directory: ${{runner.workspace}}
      shell: bash
      run: ./test
