name: Build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        flags:
          - "-O0 -ggdb3"
          - "-O2"
        compiler:
          - { CC: gcc, CXX: g++ }
          - { CC: clang, CXX: clang++ }

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Boost
      run: sudo apt install libboost-all-dev
    - name: Build
      env:
        CFLAGS: ${{ matrix.flags }} -fsanitize=address
        CXXFLAGS: ${{ matrix.flags }} -fsanitize=address
        LDFLAGS: -fsanitize=address
      run: make

    - name: Test
      run: ./test
